name: metrics-server merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily
  pull_request:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-metrics-server.yaml'
  push:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-metrics-server.yaml'

jobs:
  metrics-server-merge:
    uses: ./.github/workflows/merge-flow.yaml
    with:
      upstream: kubernetes-sigs/metrics-server
      downstream: openshift/kubernetes-metrics-server
      sandbox: rhobs/kubernetes-metrics-server
      restore-downstream: >-
         OWNERS
         charts/OWNERS
      restore-upstream: >-
         go.mod
         go.sum
      downstream-version-expression: |
        sed -n -E 's/^.*newTag: *(v[0-9]+\.[0-9]+\.[0-9]+).*$/\1/p' https://raw.githubusercontent.com/openshift/kubernetes-metrics-server/main/manifests/components/release/kustomization.yaml
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
