name: Prometheus RC versions tester

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily
  pull_request:
    paths:
    - '.github/workflows/merge-flow.yaml'
    # TODO: test using prom merge
    - '.github/workflows/merge-prometheus.yaml'
    - '.github/workflows/test-rc-prometheus.yaml'
  push:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-prometheus.yaml'
    - '.github/workflows/test-rc-prometheus.yaml'
jobs:
  prometheus-rc-test:
  uses: ./.github/workflows/merge-prometheus.yaml
    # uses: ./.github/workflows/merge-flow.yaml
    with:
      upstream-version-pattern: "^\d+\.\d+\.\d+-rc\.\d+$"

    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
